package org.stone.model;

import org.stone.model.base.BaseDatasource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Datasource extends BaseDatasource<Datasource> {
	public static final Datasource dao = new Datasource();
}
