package org.stone.model;

import org.stone.model.base.BaseMenus;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Menus extends BaseMenus<Menus> {
	public static final Menus dao = new Menus();
}
